### ISSUE TITLE
"Error: EACCESS: permission denied" when Running "npm run dev"

### ISSUE THREAD

**Issue by coffeepostal** [bencodezen/vuepress-blog-boilerplate#35]
I'm having an issue where when I try to run `npm run dev` I'm getting a permissions error:

```
coffeepostal@Adams-Mac-Pro:~/Code/vuepress-blog-boilerplate$ npm run dev

> vuepress-blog@0.11.0-beta dev /Users/coffeepostal/Code/vuepress-blog-boilerplate
> vuepress dev src

wait Extracting site metadata...
Error: EACCES: permission denied, mkdir '/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/.temp'
    at Object.mkdirSync (fs.js:753:3)
    at Object.mkdirsSync (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at createTemp (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/prepare/AppContext.js:464:8)
    at new AppContext (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/prepare/AppContext.js:51:37)
    at Function.getInstance (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/prepare/AppContext.js:28:30)
    at prepare (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/prepare/index.js:16:33)
    at prepareServer (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/dev.js:28:32)
    at module.exports (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/@vuepress/core/lib/dev.js:4:40)
    at args (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/vuepress/lib/util.js:35:12)
    at CAC.cli.command.option.option.option.option.option.option.option.option.action (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/vuepress/lib/registerCoreCommands.js:34:23)
    at CAC.runMatchedCommand (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/cac/dist/index.js:787:38)
    at CAC.parse (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/cac/dist/index.js:707:18)
    at CLI (/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/vuepress/lib/util.js:23:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepress-blog@0.11.0-beta dev: `vuepress dev src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuepress-blog@0.11.0-beta dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coffeepostal/.npm/_logs/2019-02-26T06_15_43_636Z-debug.log
```

I initially got an error on install, but running it via `sudo` cleared that up. I read the [Unexpected end of JSON input while parsing](https://github.com/bencodezen/vuepress-blog-boilerplate/issues/11) issue, and cleaned my NPM cache, but I'm still getting the error. Additionally, here's the log file that is referenced at the end of the error out:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.8.0
3 info using node@v10.15.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vuepress-blog@0.11.0-beta~predev: vuepress-blog@0.11.0-beta
6 info lifecycle vuepress-blog@0.11.0-beta~dev: vuepress-blog@0.11.0-beta
7 verbose lifecycle vuepress-blog@0.11.0-beta~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vuepress-blog@0.11.0-beta~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/coffeepostal/Code/vuepress-blog-boilerplate/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle vuepress-blog@0.11.0-beta~dev: CWD: /Users/coffeepostal/Code/vuepress-blog-boilerplate
10 silly lifecycle vuepress-blog@0.11.0-beta~dev: Args: [ '-c', 'vuepress dev src' ]
11 silly lifecycle vuepress-blog@0.11.0-beta~dev: Returned: code: 1  signal: null
12 info lifecycle vuepress-blog@0.11.0-beta~dev: Failed to exec dev script
13 verbose stack Error: vuepress-blog@0.11.0-beta dev: `vuepress dev src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vuepress-blog@0.11.0-beta
15 verbose cwd /Users/coffeepostal/Code/vuepress-blog-boilerplate
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v10.15.1
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error vuepress-blog@0.11.0-beta dev: `vuepress dev src`
22 error Exit status 1
23 error Failed at the vuepress-blog@0.11.0-beta dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm still fairly new to Vue, so this may be an old hat issue, but it's stumping me. Thanks!

**Comment by bencodezen** [comment]
Hey @coffeepostal! Sorry to hear that you're running into this error. Have you tried running sudo with the `npm run dev` as well?

**Comment by coffeepostal** [comment]
You know, @bencodezen, I thought I had, but I tried it again, before responding, and it worked, so I must not have. Thank you for such a quick response, and so sorry to bother you, I'm a big fan of your contributions to the Vue community. Thanks again!

**Comment by alijahanpak** [comment]
use :  sudo vuepress dev
