### ISSUE TITLE
build fails 

### ISSUE THREAD

**Issue by iandstanley** [bencodezen/vuepress-blog-boilerplate#47]
Hi Nick 

great tool for blog creation .. I've been testing it out locally over the weekend and then tried to publish on Netlify and ran into trouble.

```
11:18:14 AM: git clone https://github.com/raspberry-pi-dev/raspi-blog
11:18:15 AM: Preparing Git Reference refs/heads/master
11:18:15 AM: Error checking out submodules: fatal: No url found for submodule path 'vuepress-blog-boilerplate' in .gitmodules
11:18:15 AM: Failing build: Failed to prepare repo
11:18:15 AM: failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'vuepress-blog-boilerplate' in .gitmodules
: exit status 128
```

I've tried this two ways:

1. Cloning the repo and then removing the upstream. I did this with the repo https://github.com/raspberry-pi-dev/raspi-blog at first and I **got error the message above**
1. Tried again with something more vanilla. I just made a simple fork of your repo at https://github.com/raspberry-pi-dev/vuepress-blog-boilerplate then pushed into the blog directory a few md files and jpgs

Both of these work fine locally running **sudo vuepress dev src**

But when I push them to github the Netlify build fails. The same Netlify build process & settings that I use for other vuepress (non-blog) website

**Comment by iandstanley** [comment]
**AS A COMPARISON**

With the fork option (#2 above)  I get the following build log which complains about stuff I cant figure out but different from above (#1)

```
11:19:46 AM: Build ready to start
11:19:48 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
11:19:48 AM: build-image tag: v3.3.2
11:19:48 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
11:19:48 AM: Fetching cached dependencies
11:19:49 AM: Failed to fetch cache, continuing with build
11:19:49 AM: Starting to prepare the repo for build
11:19:49 AM: No cached dependencies found. Cloning fresh repo
11:19:49 AM: git clone https://github.com/raspberry-pi-dev/vuepress-blog-boilerplate
11:19:50 AM: Preparing Git Reference refs/heads/master
11:19:51 AM: Starting build script
11:19:51 AM: Installing dependencies
11:19:52 AM: Downloading and installing node v10.16.2...
11:19:52 AM: Downloading https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.xz...
11:19:53 AM: 
###########
11:19:53 AM:                     16.0%
11:19:53 AM: 
######################################################################## 100.
11:19:53 AM: 0%
11:19:53 AM: Computing checksum with sha256sum
11:19:53 AM: Checksums matched!
11:19:56 AM: Now using node v10.16.2 (npm v6.9.0)
11:19:56 AM: Attempting ruby version 2.6.2, read from environment
11:19:58 AM: Using ruby version 2.6.2
11:19:58 AM: Using PHP version 5.6
11:19:58 AM: Started restoring cached node modules
11:19:58 AM: Finished restoring cached node modules
11:19:58 AM: Started restoring cached yarn cache
11:19:58 AM: Finished restoring cached yarn cache
11:19:58 AM: Installing yarn at version 1.17.0
11:19:59 AM: Installing Yarn!
11:19:59 AM: > Downloading tarball...
11:19:59 AM: [1/2]: https://yarnpkg.com/downloads/1.17.0/yarn-v1.17.
11:19:59 AM: 0.tar.gz --> /tmp/yarn.tar.gz.BIA6n6OgeO
11:19:59 AM:   % Total    % Received % Xferd  Average Speed
11:19:59 AM: Time    Time     Time  Current
11:19:59 AM: Dload  Upload   Total   Spent    Left  Speed
11:19:59 AM: 
  0     0
11:19:59 AM:  0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11:19:59 AM: 
100    93  100    93    0     0    163      0 --:--:-- --:--:-- --:--:--   163
11:19:59 AM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
11:19:59 AM:    0
11:19:59 AM: 1
11:19:59 AM: 0
11:19:59 AM: 0
11:19:59 AM: 6
11:19:59 AM: 0
11:19:59 AM: 9
11:19:59 AM: 0
11:20:00 AM: 6
11:20:00 AM: 0
11:20:00 AM: 9
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 6
11:20:00 AM: 3
11:20:00 AM: 6
11:20:00 AM: 0
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -  2397
11:20:00 AM: 
100 1213k  100 1213k    0     0   800k
11:20:00 AM: 0  0:00:01  0:00:01 --:--:--  800k
11:20:00 AM: [2/2]: https://yarnpkg.com/downloads/1.17.
11:20:00 AM: 0/yarn-v1.17.0.tar.gz.asc --> /tmp/yarn.tar.gz.BIA6n6OgeO.asc
11:20:00 AM: 1
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 9
11:20:00 AM: 7
11:20:00 AM: 1
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 9
11:20:00 AM: 7
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 2
11:20:00 AM: 7
11:20:00 AM: 2
11:20:00 AM: 2
11:20:00 AM: 0
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM: :
11:20:00 AM: -
11:20:00 AM: -
11:20:00 AM:  --:--:--  272
11:20:00 AM: 2
11:20:00 AM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11:20:00 AM: 
100   613    0   613    0     0   3399      0 --:--:-- --:--:-- --:--:--  598k
11:20:00 AM: 1
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 8
11:20:00 AM: 3
11:20:00 AM: 2
11:20:00 AM: 1
11:20:00 AM: 0
11:20:00 AM: 0
11:20:00 AM: 8
11:20:00 AM: 3
11:20:00 AM: 2    0     0   376
11:20:00 AM: 4      0 --:--:-- --:--:-- --:--:--  3764
11:20:00 AM: > Verifying integrity...
11:20:00 AM: gpg: Signature made Fri 14 Jun 2019 06:55:58 PM UTC using RSA key ID 69475BAA
11:20:00 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
11:20:00 AM: gpg: WARNING: This key is not certified with a trusted signature!
11:20:00 AM: gpg:          There is no indication that the signature belongs to the owner.
11:20:00 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
11:20:00 AM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
11:20:00 AM: > GPG signature looks good
11:20:00 AM: > Extracting to ~/.yarn...
11:20:00 AM: > Adding to $PATH...
11:20:00 AM: > We've added the following to your /opt/buildhome/.profile
11:20:00 AM: > If this isn't the profile of your current shell then please add the following to your correct profile:
11:20:00 AM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
11:20:00 AM: 
11:20:01 AM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
11:20:02 AM: Installing NPM modules using Yarn version 1.17.0
11:20:03 AM: yarn install v1.17.0
11:20:03 AM: [1/4] Resolving packages...
11:20:03 AM: [2/4] Fetching packages...
11:20:20 AM: info fsevents@1.2.4: The platform "linux" is incompatible with this module.
11:20:20 AM: info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
11:20:20 AM: [3/4] Linking dependencies...
11:20:20 AM: warning "vuepress > @vuepress/core > @vue/babel-preset-app > @vue/babel-preset-jsx@1.0.0-beta.1" has unmet peer dependency "@vue/babel-helper-vue-jsx-merge-props@^0.1.0".
11:20:20 AM: warning "vuepress > @vuepress/core > @vue/babel-preset-app > @vue/babel-preset-jsx > @vue/babel-plugin-transform-vue-jsx@1.0.0-beta.1" has incorrect peer dependency "@vue/babel-helper-vue-jsx-merge-props@^0.1.0".
11:20:27 AM: [4/4] Building fresh packages...
11:20:27 AM: Done in 24.19s.
11:20:27 AM: NPM modules installed using Yarn
11:20:28 AM: Started restoring cached go cache
11:20:28 AM: Finished restoring cached go cache
11:20:28 AM: unset GOOS;
11:20:28 AM: unset GOARCH;
11:20:28 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
11:20:28 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
11:20:28 AM: go version >&2;
11:20:28 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
11:20:28 AM: go version go1.12 linux/amd64
11:20:28 AM: Installing missing commands
11:20:28 AM: Verify run directory
11:20:28 AM: Executing user command: vuepress build docs
11:20:29 AM: wait Extracting site metadata...
11:20:29 AM: tip Apply theme @vuepress/theme-default
11:20:29 AM: tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
11:20:29 AM: tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
11:20:29 AM: tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
11:20:29 AM: tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
11:20:29 AM: tip Apply plugin rss (i.e. "vuepress-plugin-rss") ...
11:20:31 AM: [10:20:31 AM] Compiling Client
11:20:31 AM: [10:20:31 AM] Compiling Server
11:20:31 AM: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
11:20:43 AM: [10:20:43 AM] Compiled Server in 12s
11:20:51 AM: [10:20:51 AM] Compiled Client in 20s
11:20:51 AM: wait Rendering static HTML...
11:20:51 AM: Rendering page: /
11:20:51 AM: ReferenceError: window is not defined
11:20:51 AM:     at inject (server-bundle.js:6640:8)
11:20:51 AM:     at server-bundle.js:7135:9
11:20:51 AM:     at Array.forEach (<anonymous>)
11:20:51 AM:     at createApp (server-bundle.js:7133:19)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7174:22)
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at new F (server-bundle.js:174:28)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7173:10)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8456:15
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8418:14
11:20:51 AM:     at Object.renderToString (/opt/build/repo/node_modules/vue-server-renderer/build.js:8594:9)
11:20:51 AM:     at renderPage (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:151:29)
11:20:51 AM:     at build (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:76:26)
11:20:51 AM: 
11:20:51 AM: Rendering page: /learn/
11:20:51 AM: ReferenceError: window is not defined
11:20:51 AM:     at inject (server-bundle.js:6640:8)
11:20:51 AM:     at server-bundle.js:7135:9
11:20:51 AM:     at Array.forEach (<anonymous>)
11:20:51 AM:     at createApp (server-bundle.js:7133:19)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7174:22)
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at new F (server-bundle.js:174:28)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7173:10)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8456:15
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8418:14
11:20:51 AM:     at Object.renderToString (/opt/build/repo/node_modules/vue-server-renderer/build.js:8594:9)
11:20:51 AM:     at renderPage (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:151:29)
11:20:51 AM:     at build (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:76:26)
11:20:51 AM: 
11:20:51 AM: Rendering page: /404.html
11:20:51 AM: ReferenceError: window is not defined
11:20:51 AM:     at inject (server-bundle.js:6640:8)
11:20:51 AM:     at server-bundle.js:7135:9
11:20:51 AM:     at Array.forEach (<anonymous>)
11:20:51 AM:     at createApp (server-bundle.js:7133:19)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7174:22)
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at new F (server-bundle.js:174:28)
11:20:51 AM:     at module.exports.__webpack_exports__.default (server-bundle.js:7173:10)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8456:15
11:20:51 AM:     at new Promise (<anonymous>)
11:20:51 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.js:8418:14
11:20:51 AM:     at Object.renderToString (/opt/build/repo/node_modules/vue-server-renderer/build.js:8594:9)
11:20:51 AM:     at renderPage (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:151:29)
11:20:51 AM:     at build (/opt/build/repo/node_modules/@vuepress/core/lib/build.js:76:26)
11:20:51 AM: 
11:20:51 AM: 
11:20:51 AM: RSS has been generated!
11:20:51 AM: success Generated static files in public.
11:20:51 AM: Skipping functions preparation step: no functions directory set
11:20:51 AM: Caching artifacts
11:20:51 AM: Started saving node modules
11:20:51 AM: Finished saving node modules
11:20:51 AM: Started saving yarn cache
11:20:51 AM: Finished saving yarn cache
11:20:51 AM: Started saving pip cache
11:20:51 AM: Finished saving pip cache
11:20:51 AM: Started saving emacs cask dependencies
11:20:51 AM: Finished saving emacs cask dependencies
11:20:51 AM: Started saving maven dependencies
11:20:51 AM: Finished saving maven dependencies
11:20:51 AM: Started saving boot dependencies
11:20:51 AM: Finished saving boot dependencies
11:20:51 AM: Started saving go dependencies
11:20:51 AM: Finished saving go dependencies
11:20:55 AM: Build script success
11:20:55 AM: Failing build: Failed to build site
11:20:55 AM: failed during stage 'building site': Deploy directory 'docs/.vuepress/dist' does not exist
11:20:55 AM: Finished processing build request in 1m6.878616798s
```

**Comment by iandstanley** [comment]
The first option (my original repo) seems to be the easiest to fix but having no idea about submodules don't even no where to start

```
GitHub/raspi-blog $ find . -name .gitmodules -print
./node_modules/hogan.js/.gitmodules
./node_modules/extsprintf/.gitmodules
```



```
GitHub/raspi-blog $ cat ./node_modules/hogan.js/.gitmodules
[submodule "test/spec"]
	path = test/spec
	url = https://github.com/mustache/spec.git
[submodule "test/qunit-logging"]
	path = test/qunit-logging
	url = git://github.com/keithamus/qunit-logging.git
[submodule "test/qunit"]
	path = test/qunit
	url = git://github.com/jquery/qunit.git

GitHub/raspi-blog $ cat ./node_modules/extsprintf/.gitmodules
[submodule "deps/catest"]
	path = deps/catest
	url = https://github.com/joyent/catest
```


I still get the following build errors: 

```
11:48:54 AM: Build ready to start
11:48:56 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
11:48:56 AM: build-image tag: v3.3.2
11:48:56 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
11:48:56 AM: Fetching cached dependencies
11:48:56 AM: Starting to download cache of 255.0KB
11:48:56 AM: Finished downloading cache in 103.699392ms
11:48:56 AM: Starting to extract cache
11:48:56 AM: Failed to fetch cache, continuing with build
11:48:56 AM: Starting to prepare the repo for build
11:48:56 AM: No cached dependencies found. Cloning fresh repo
11:48:56 AM: git clone https://github.com/raspberry-pi-dev/raspi-blog
11:48:57 AM: Preparing Git Reference refs/heads/master
11:48:58 AM: Error checking out submodules: fatal: No url found for submodule path 'vuepress-blog-boilerplate' in .gitmodules
11:48:58 AM: Failing build: Failed to prepare repo
11:48:58 AM: failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'vuepress-blog-boilerplate' in .gitmodules: exit status 128
```

I've also tried specifically adding extsprintf as a dependancy and still no joy

Any ideas?

**Comment by bencodezen** [comment]
Hey @iandstanley. That is definitely odd. The current build seems to be okay... 

What are your build settings in Netlify?

**Comment by bencodezen** [comment]
So I checked out your repo and it looks like there's a weird submodule folder in there. Did you try forking the repo? Or did you do some other method of copying and pasting?

**Comment by bencodezen** [comment]
Hey @iandstanley! Haven't heard from you in a bit, so I'm hoping everything got solved. If not, feel free to re-open / file a new issue. Thank you!
