### ISSUE TITLE
Cannot find module .vuepress/theme

### ISSUE THREAD

**Issue by Kerwood** [bencodezen/vuepress-blog-boilerplate#60]
When running your boilerplate, an error/warning show up regarding the theme.
When running below command you easily se the issue.
```
$ vuepress dev --debug --no-clear-screen src
...
tip Apply local theme at /home/kerwood/Git/vuepress-app/src/.vuepress/theme...
debug Error: Cannot find module '/home/kerwood/Git/vuepress-app/src/.vuepress/theme'
Require stack:
- /home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/moduleResolver.js
- /home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/index.js
- /home/kerwood/Git/vuepress-app/node_modules/vuepress/lib/checkEnv.js
- /home/kerwood/Git/vuepress-app/node_modules/vuepress/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at ModuleResolver.resolvePathPackage (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/moduleResolver.js:126:40)
    at Object.tryChain [as default] (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/tryChain.js:13:24)
    at ModuleResolver.resolve (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/moduleResolver.js:84:44)
    at PluginAPI.normalizePlugin (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/core/lib/node/plugin-api/index.js:121:39)
    at resolveTheme (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/core/lib/node/loadTheme.js:126:23)
    at loadTheme (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/core/lib/node/loadTheme.js:36:17)
    at App.process (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/core/lib/node/App.js:105:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async dev (/home/kerwood/Git/vuepress-app/node_modules/@vuepress/core/lib/index.js:17:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/moduleResolver.js',
    '/home/kerwood/Git/vuepress-app/node_modules/@vuepress/shared-utils/lib/index.js',
    '/home/kerwood/Git/vuepress-app/node_modules/vuepress/lib/checkEnv.js',
    '/home/kerwood/Git/vuepress-app/node_modules/vuepress/cli.js'
  ]
}
warning An error was encountered in theme "/home/kerwood/Git/vuepress-app/src/.vuepress/theme"
tip Apply theme local ...
debug theme local /home/kerwood/Git/vuepress-app/src/.vuepress/theme
debug parentTheme undefined undefined
...
```

I cant really figure out the issue.

**Comment by bencodezen** [comment]
@Kerwood Are you getting this error after a simple clone of the repo? Or did you run a separate installation of VuePress? My initial guess is that the versions are out of sync.

**Comment by Kerwood** [comment]
Yes, if you clone this repo and run it, you will get this error.
```
git clone https://github.com/bencodezen/vuepress-blog-boilerplate.git
cd vuepress-blog-boilerplate
npm install
node_modules/vuepress/cli.js dev --debug --no-clear-screen src
```

**Comment by Kerwood** [comment]
Adding an empty `index.js` file in the theme folder will "fix" this issue.

**Comment by bencodezen** [comment]
Ack. Sorry for the delay @Kerwood. That is weird. I definitely need to update this boilerplate so it accounts for some of the newer features of VuePress. I'll keep this issue open for now to remind me to make sure everything is good on the theme side when I update it.

**Comment by bencodezen** [comment]
Closing since this project will no longer be maintained.
